'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useHqClock} from '@/components/use-hq-clock';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {json} from '@/lib/hq-client';
import {clientId} from '@/lib/client-id';
import {chicagoWall} from '@/lib/consignment';
import {calendarDay} from '@/lib/content-calendar';
import {recordedTime,type HqContext,type HqRecord,type Project} from '@/lib/hq-model';
import {budgetTotals,type SpendEntry,type SpendSummary} from '@/lib/hq-operations';
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
type Spending={summary:SpendSummary;entries:SpendEntry[];nextOffset:number|null};
export function HqSpending({project,context:c}:{project:HqRecord<Project>;context:HqContext}){
 const [spending,setSpending]=useState<Spending|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[amount,setAmount]=useState(''),[category,setCategory]=useState('advertising'),[date,setDate]=useState(''),[channel,setChannel]=useState(''),[note,setNote]=useState(''),[reverse,setReverse]=useState<SpendEntry|null>(null),[reason,setReason]=useState(''),[message,setMessage]=useState('');
 const now=useHqClock();
 const attempt=useRef<{body:string;id:string}|null>(null),lock=useRef(false);
 const fetchSpending=useCallback((offset=0,signal?:AbortSignal)=>json<Spending>('/api/hq?kind=spend&id='+encodeURIComponent(project.id)+'&offset='+offset,{signal}),[project.id]);
 const load=useCallback(async(offset=0)=>{const value=await fetchSpending(offset);setSpending(old=>offset&&old?{...value,entries:[...old.entries,...value.entries]}:value);setError('');},[fetchSpending]);
 useEffect(()=>{const controller=new AbortController();void fetchSpending(0,controller.signal).then(value=>{if(!controller.signal.aborted){setSpending(value);setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[fetchSpending]);
 useEffect(()=>{const refresh=()=>void load().catch(e=>setError(e.message));window.addEventListener('hq-records-changed',refresh);return()=>window.removeEventListener('hq-records-changed',refresh);},[load]);
 const authorized=project.data.owner===c.staffId||c.canApproveBudget;
 async function save(fields:Record<string,unknown>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');const body=JSON.stringify(fields);if(attempt.current?.body!==body)attempt.current={body,id:clientId()};try{await json('/api/hq',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,id:attempt.current.id,projectId:project.id})});await load();setAmount('');setNote('');setReverse(null);setReason('');attempt.current=null;setMessage('Actual spending saved. Approved budgets and purchases were not changed.');window.dispatchEvent(new Event('hq-records-changed'));}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 const totals=spending?budgetTotals(project.data,spending.summary):null;
 return <section className="panel"><h2>Actual spending</h2><p className="muted">Manual records only. This never buys advertising, pays invoices or increases approval. Planned allocations and actual spending are compared separately.</p>
 {error&&<div role="alert"><p>{error}</p><Button variant="outline" onClick={()=>void load().catch(e=>setError(e.message))}>Reload spending</Button></div>}{message&&<p role="status">{message}</p>}
 {totals?<><dl className="hq-budget-grid"><div><dt>Approved project amount</dt><dd>{totals.approved===null?'Not approved':money(totals.approved)}</dd></div><div><dt>Planned channel allocations</dt><dd>{money(totals.planned)}</dd></div><div><dt>Advertising actual</dt><dd>{money(totals.advertisingCents)}</dd></div><div><dt>Creative actual</dt><dd>{money(totals.creativeCents)}</dd></div><div><dt>Total actual spending</dt><dd>{money(totals.totalCents)}</dd></div><div><dt>Remaining after actual spend</dt><dd>{totals.remaining===null?'No approved budget':money(totals.remaining)}</dd></div></dl>{totals.overage>0&&<p className="notice error" role="status">Over budget by {money(totals.overage)}. Recorded actuals exceed the approved amount.</p>}{totals.unapprovedSpend&&<p className="notice error" role="status">{money(totals.totalCents)} spent without an approved project budget.</p>}</>:!error&&<p role="status">Loading actual spending…</p>}
 {authorized&&<details className="hq-details"><summary>Record actual spend</summary><form className="hq-form" onSubmit={e=>{e.preventDefault();void save({action:'spend',category,amountCents:Math.round(Number(amount)*100),spentOn:date,channel,note});}}><fieldset disabled={busy} className="campaign-fields"><div className="two-fields"><label className="field"><span>Cost type</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="advertising">Advertising</option><option value="creative">Creative production</option></select></label><label className="field"><span>Actual amount (USD)</span><Input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><label className="field"><span>Spending date (America/Chicago)</span><Input required type="date" value={date} max={now===null?undefined:chicagoWall(now).slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Channel (optional, including unplanned spending)</span><Input maxLength={80} value={channel} onChange={e=>setChannel(e.target.value)}/></label><label className="field"><span>Spending note / invoice reference</span><Textarea required maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><Button type="submit">Record actual spending</Button></fieldset></form></details>}
 {!authorized&&<p className="muted">The project owner or a configured budget approver records actual spending.</p>}
 {reverse&&<form className="hq-form notice" onSubmit={e=>{e.preventDefault();void save({action:'spend-reverse',reverses:reverse.id,note:reason});}}><h3>Reverse {money(reverse.amount_cents)} entry</h3><p>The original remains in history. A matching negative correction removes its amount from actual totals.</p><label className="field"><span>Correction reason</span><Textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="button-row"><Button type="submit" disabled={busy}>Save reversing entry</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setReverse(null)}>Cancel correction</Button></div></form>}
 <ul className="hq-deliverables">{spending?.entries.map(e=><li key={e.id}><div><strong>{money(e.amount_cents)} · {e.category==='advertising'?'Advertising':'Creative'}</strong><p>{calendarDay(e.spent_on)}{e.channel?' · '+e.channel:''}</p><p>{e.note}</p><p className="muted">Recorded by {c.staff.find(s=>s.id===e.actor)?.name||e.actor} · {recordedTime(e.created_at)}{e.reverses?' · Reversing entry':e.reversed?' · Reversed':''}</p></div>{authorized&&!e.reverses&&!e.reversed&&<Button variant="outline" disabled={busy} onClick={()=>{setReverse(e);setReason('');}}>Correct entry</Button>}</li>)}</ul>
 {spending&&!spending.entries.length&&<p>No actual spending recorded. Approved amounts and plans are not counted as expenses.</p>}{spending?.nextOffset!==null&&spending?.nextOffset!==undefined&&<Button variant="outline" onClick={()=>void load(spending.nextOffset!).catch(e=>setError(e.message))}>Load earlier spending</Button>}
 </section>;
}
