'use client';
import {EmptyState, PageHelp, SectionHeader, StatusBadge} from '@/components/hq-ui';
import {workStatus} from '@/lib/hq-presentation';
import {useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {useHqClock} from '@/components/use-hq-clock';
import {useHqContext} from '@/components/use-hq-context';
import {json} from '@/lib/hq-client';
import {chicagoWall,type CampaignRecord} from '@/lib/consignment';
import {calendarDay,calendarTime,type CalendarPost} from '@/lib/content-calendar';
import {canWork,productionStatuses,type Deliverable,type HqRecord,type Project} from '@/lib/hq-model';
import {addDays,filterSchedule,personName,scheduleRows,type ScheduleFilters,type ScheduleRow} from '@/lib/hq-operations';
const initial:ScheduleFilters={mode:'publication',person:'',project:'',format:'',platform:'',status:'',from:'',to:''};
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Record<string,string>}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>;}
export function HqSchedule({records,projects,posts,campaigns,onChanged,onLegacy}:{records:HqRecord<Deliverable>[];projects:HqRecord<Project>[];posts:CalendarPost[];campaigns:CampaignRecord[];onChanged:()=>Promise<unknown>;onLegacy:()=>void}){
 const {context,error:contextError,reload}=useHqContext(),[choices,setFilters]=useState(initial),[editing,setEditing]=useState<ScheduleRow|null>(null),[time,setTime]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const now=useHqClock(),day=now===null?'':chicagoWall(now).slice(0,10),from=choices.from||day;
 const filters={...choices,from,to:choices.to||(from?addDays(from,30):'')};
 const update=(patch:Partial<ScheduleFilters>)=>{setFilters(f=>{const next={...filters,...f,...patch};const start=next.from||day,end=next.to||addDays(start,30);if(start&&(end<start||end>addDays(start,92)))next.to=patch.from?addDays(start,30):end<start?start:addDays(start,92);return next;});setEditing(null);};
 if(contextError)return <div role="alert">{contextError}<Button onClick={reload}>Retry calendar</Button></div>;
 if(!context||!filters.from)return <p role="status">Loading the shared calendar…</p>;
 const rows=scheduleRows(records,projects,filters.mode,posts,filters.from,filters.to),shown=filterSchedule(rows,filters);
 async function saveDate(){const record=records.find(r=>r.id===editing?.id);if(!record||busy)return;setBusy(true);setError('');try{await json('/api/hq',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reschedule',id:record.id,version:record.data.version,field:filters.mode==='production'?'productionDue':'publishAt',time})});await onChanged();window.dispatchEvent(new Event('hq-records-changed'));setEditing(null);setMessage('Date saved to the deliverable. Today and project views use this same record.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><SectionHeader title="Schedule" description="Production deadlines and publication plans · Central time"/>
 <div className="hq-view-switch" role="group" aria-label="Calendar dates"><Button aria-pressed={filters.mode==='publication'} variant="ghost" onClick={()=>update({mode:'publication',status:''})}>Publication plans</Button><Button aria-pressed={filters.mode==='production'} variant="ghost" onClick={()=>update({mode:'production',platform:'',status:''})}>Production deadlines</Button></div>
 <div className="hq-filter-grid"><label className="field"><span>From date</span><Input type="date" value={filters.from} onChange={e=>e.target.value&&update({from:e.target.value})}/></label><label className="field"><span>Through date</span><Input type="date" min={filters.from} max={addDays(filters.from,92)} value={filters.to} onChange={e=>e.target.value&&update({to:e.target.value})}/></label>
 <Filter label="Person" value={filters.person} onChange={person=>update({person})} options={{'':'All people',unassigned:'Unassigned',...Object.fromEntries(context.staff.map(s=>[s.id,s.name]))}}/>
 <Filter label="Project" value={filters.project} onChange={project=>update({project})} options={{'':'All projects',standalone:'Standalone / no project',...Object.fromEntries(projects.map(p=>[p.id,p.data.title])),...Object.fromEntries(campaigns.map(c=>['legacy:'+c.id,'Legacy campaign: '+c.data.name]))}}/>
 <Filter label="Format" value={filters.format} onChange={format=>update({format})} options={{'':'All formats',missing:'Format not recorded',...Object.fromEntries([...new Set(records.map(r=>r.data.format).filter(Boolean))].map(v=>[v,v]))}}/>
 <Filter label="Platform" value={filters.platform} onChange={platform=>update({platform})} options={{'':'All platforms',...Object.fromEntries([...new Set(rows.map(r=>r.platform).filter(Boolean))].map(v=>[v,v]))}}/>
 <Filter label="Status" value={filters.status} onChange={status=>update({status})} options={{'':'All statuses',...productionStatuses,...(filters.mode==='publication'?{planned:'Planned',scheduled:'Scheduled',published:'Published',...Object.fromEntries([...new Set(posts.map(p=>p.data.status))].map(s=>['legacy:'+s,'Legacy '+s+' (unconfirmed)']))}:{})}}/>
 </div><p className="muted">Recurring entries are expanded for up to 93 days. Use their existing editor to change a series.</p>
 {error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status">{message}</p>}
 {editing&&<form className="hq-form notice" onSubmit={e=>{e.preventDefault();void saveDate();}}><h3>Edit {filters.mode==='production'?'production deadline':'publication plan'} · {editing.title}</h3><p>Saving changes the deliverable itself and clears any current approval. Publication plans apply to all its Planned destinations. Confirmed schedules must be cancelled on the platform first.</p><label className="field"><span>New date and time (America/Chicago)</span><Input type="datetime-local" value={time} onChange={e=>setTime(e.target.value)} disabled={busy}/></label><p className="muted">Leave empty to remove the plan. Ambiguous or missing daylight-saving times must be changed to a clear time.</p><div className="button-row"><Button disabled={busy} type="submit">Save source date</Button><Button variant="outline" type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel date edit</Button></div></form>}
 <ul className="hq-deliverables">{shown.map(r=>{const record=records.find(d=>d.id===r.id),project=projects.find(p=>p.id===r.projectId)?.data,locked=record&&(record.data.status==='done'||Object.values(record.data.publications).some(p=>p.status!=='planned'));
 return <li key={r.key}><div>{r.kind==='deliverable'?<Link href={'/projects/work/'+r.id}>{r.title}</Link>:<a href="#existing-calendar" onClick={onLegacy}>{r.title}{r.recurring?' · recurring series':''}</a>}<p>{r.date?calendarDay(r.date)+' · '+calendarTime(r.date):'Date not set'}{r.platform?' · '+r.platform:''}</p><p>Owner: {personName(r.owner,context.staff)}{r.publisher?' · Publisher: '+personName(r.publisher,context.staff):''}</p><p className="muted">{r.kind==='legacy'?'Preserved legacy record; no HQ confirmation inferred.':r.action}</p></div><div>{r.kind==='legacy'?<span className="tag">{r.stateLabel}</span>:<StatusBadge status={r.status==='published'?'complete':record?workStatus(record.data,project):'not_started'} detail={r.stateLabel}/>}{r.kind==='deliverable'&&record&&canWork(record.data,project,context)&&(locked?<p className="muted">Confirmed / completed · date locked</p>:<Button variant="outline" disabled={busy} onClick={()=>{setEditing(r);setTime(filters.mode==='production'?record.data.productionDue:record.data.publishAt);setError('');setMessage('');}}>Edit date</Button>)}</div></li>;})}</ul>
 {!shown.length&&<EmptyState title="No work matches these filters" description="Adjust the dates or filters, or add a task in Work." action={<Button variant="outline" onClick={()=>update({person:'',project:'',format:'',platform:'',status:''})}>Clear Filters</Button>}/>}
 <PageHelp title="How dates and confirmations work"><p>Planned dates never imply scheduling or publication. Missing dates remain visible for planning. Publishing is confirmed separately for each platform.</p></PageHelp></section>;
}
