'use client';
import {chicagoDay as date} from '@/lib/content-radar/dates';
import Link from 'next/link';
import {SourcePanel} from './sources';
import { useEffect, useRef, useState, useMemo } from 'react';
import {HqSubnavigation,HqTabPanel,useHqTab} from '@/components/hq-subnavigation';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import {tabHref} from '@/lib/hq-tabs';
const researchTabs=[{id:'feed',label:'Feed'},{id:'releases',label:'Release verification'},{id:'chase',label:'Chase Cards'},{id:'drafts',label:'Drafts'},{id:'sources',label:'Sources'}];
import { Button } from '@/components/ui/button';
import { Collapsible,CollapsibleTrigger,CollapsibleContent } from '@/components/ui/collapsible';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger } from '@/components/ui/dialog';
import { Radar as RadarIcon,Plus,ArrowUpRight,Bookmark,X,Search,RefreshCw,CalendarDays,Radio } from 'lucide-react';
import { CATEGORIES,PRIORITIES,STATUSES,KINDS,VERIFY,DRAFT_STATUSES,CHANNELS,emptyFilters } from '@/lib/content-radar/model';
import type { RadarData,Filters,Item,Draft,RadarCommand } from '@/lib/content-radar/model';

function Choice({label,value,options,onChange,disabled=false}:{label:string;value:string;options:readonly string[]|{value:string;label:string}[];disabled?:boolean;onChange:(v:string)=>void}) {
 return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=>typeof o==='string'?<SelectItem value={o} key={o}>{o==='all'?'All':o}</SelectItem>:<SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>;
}
const initialLink={title:'',url:'',sourceId:'manual',category:'Baseball',kind:'story',priority:'normal',publishedAt:'',eventDate:'',summary:'',tags:''};
export default function Radar({organization}:{organization:string}) {
 const tab=useHqTab(researchTabs,'feed'),pathname=usePathname(),params=useSearchParams(),router=useRouter();
 const [choices,setFilters]=useState<Filters>(emptyFilters),[data,setData]=useState<RadarData|null>(null);
 const filters=useMemo(()=>choices.tab===tab?choices:{...emptyFilters,tab},[choices,tab]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[offline,setOffline]=useState(false);
 const [open,setOpen]=useState(false),[link,setLink]=useState(initialLink),[source,setSource]=useState({name:'',url:'',category:'Baseball'}),[sourceOpen,setSourceOpen]=useState(false);
 const [editing,setEditing]=useState<Draft|null>(null);
 const [collecting,setCollecting]=useState(false),[metadataNote,setMetadataNote]=useState('');
 const requestId=useRef(0);
 useEffect(()=>{void fetch('/api/content-radar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'seed-sources'})}).then(r=>{if(r.ok)setReload(n=>n+1);}).catch(()=>{});},[]);
 async function refreshSources(sourceId?:string){
  setCollecting(true);setError('');let added=0;
  try{for(let n=0;n<(sourceId?1:6);n++){setNotice(sourceId?'Checking publisher…':`Checking publisher ${n+1} of up to 6…`);const r=await fetch('/api/content-radar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh-sources',...(sourceId?{sourceId}:{})})});const j=await r.json() as {error?:string;message?:string;status?:string;source?:string;added?:number;metadata?:{title:string;summary:string;publishedAt:string|null}};if(!r.ok)throw new Error(j.error||'Collection unavailable.');added+=j.added||0;if(j.status==='skipped'){if(sourceId)setNotice(j.message||'No source is due.');break;}if(sourceId)setNotice(j.message||`${j.source}: ${j.status}. ${j.added||0} stories added.`);setReload(v=>v+1);}if(!sourceId)setNotice(`Collection finished. ${added} stories added. See Sources for individual results.`);
  }catch(e){setError((e as Error).message);}finally{setCollecting(false);setReload(n=>n+1);}
 }
 async function fillMetadata(){const url=link.url;setBusy(true);setMetadataNote('Checking the publisher…');try{const r=await fetch('/api/content-radar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'metadata',url})});const j=await r.json() as {error?:string;message?:string;status?:string;source?:string;added?:number;metadata?:{title:string;summary:string;publishedAt:string|null}};if(!r.ok)throw new Error(j.error||'Unable to check this link.');if(j.metadata){const metadata=j.metadata;setLink(v=>v.url===url?{...v,title:v.title||metadata.title,summary:v.summary||metadata.summary,publishedAt:v.publishedAt||metadata.publishedAt||''}:v);setMetadataNote('Available details added. Review them before saving.');}else setMetadataNote(j.message||'Enter details manually.');}catch(e){setMetadataNote((e as Error).message+' You can enter the details manually.');}finally{setBusy(false);}}

 useEffect(()=>{const update=()=>setOffline(!navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 useEffect(()=>{
  const controller=new AbortController(),id=++requestId.current;
  const timer=setTimeout(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams(Object.entries(filters).map(([k,v])=>[k,String(v)]));const r=await fetch('/api/content-radar?'+params,{signal:controller.signal,cache:'no-store'});const j=await r.json() as RadarData & {error?:string};if(!r.ok)throw new Error(j.error||'Unable to load research and sources.');if(id===requestId.current)setData(j);}catch(e){if(!controller.signal.aborted){setError((e as Error).message);setData(null);}}finally{if(id===requestId.current&&!controller.signal.aborted)setLoading(false);}},200);
  return()=>{clearTimeout(timer);controller.abort();};
 },[filters,reload]);
 function filter(key:keyof Filters,value:string){if(key==='tab'){router.push(tabHref(pathname,params.toString(),value));return;}setFilters({...filters,[key]:value,offset:0});}
 async function mutate(command:RadarCommand){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/content-radar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});const j=await r.json() as {error?:string};if(!r.ok){if(r.status===401||r.status===403)setData(null);throw new Error(j.error||'Unable to save.');}setNotice('Saved to '+organization);setReload(n=>n+1);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const disabled=busy||offline||collecting;
 const items=data?.items||[];
 const sources=[{value:'all',label:'All sources'},{value:'manual',label:'Manual link'},...(data?.sources||[]).map(s=>({value:s.id,label:s.name}))];
 function itemCard(item:Item){return <article className="panel radar-card" key={item.id}>
  <div className="radar-card-meta"><span className="tag blue">{item.category}</span><span className="tag">{item.kind}</span><span className={'tag radar-priority-'+item.priority}>{item.priority}</span><span className="tag">{item.status}</span></div>
  <h2>{item.title}</h2><p className="muted">{item.source_name||'Manual link'} · Published {date(item.published_at)} · Collected {date(item.collected_at)}</p>
  {item.event_date&&<p><CalendarDays size={16}/> {item.kind==='release'?'Release':'Event'} date: {date(item.event_date)}</p>}
  {item.summary&&<p className="radar-summary">{item.summary}</p>}
  <div className="radar-card-meta">{(JSON.parse(item.tags) as string[]).map(t=><span className="tag" key={t}>#{t}</span>)}</div>
  <div className="radar-verification"><span className="muted">{item.verification==='verified'?'Staff verified':'Check the original source before using this story.'}</span><Choice disabled={disabled} label="Verification" value={item.verification} options={VERIFY} onChange={verification=>void mutate({action:'verify',id:item.id,verification:verification as Item['verification']})}/></div>
  <div className="radar-actions"><Button disabled={disabled} onClick={()=>void mutate({action:'save-idea',id:item.id})}><Bookmark size={16}/>{data?.drafts.some(d=>d.item_id===item.id)?'Idea saved':'Save idea'}</Button><Button variant="outline" disabled={disabled} onClick={()=>void mutate({action:'set-status',id:item.id,status:item.status==='dismissed'?'new':'dismissed'})}><X size={16}/>{item.status==='dismissed'?'Restore':'Dismiss'}</Button><a href={item.url} target="_blank" rel="noopener noreferrer">Original source <ArrowUpRight size={16}/></a></div>
  {!!data?.publications?.filter(p=>p.item_id===item.id).length&&<details className="radar-history"><summary>Publisher coverage and updates</summary>{data.publications.filter(p=>p.item_id===item.id).map(p=><div key={p.id}><a href={p.original_url} target="_blank" rel="noopener noreferrer">{p.source_name}: {p.title}</a><p className="muted">Published {date(p.published_at)}{p.event_date?` · Release/event ${date(p.event_date)}`:''} · Observed {date(p.observed_at)}</p><p>{p.excerpt}</p></div>)}</details>}
  <details className="radar-history"><summary>Workflow history</summary><ul>{data?.history.filter(h=>h.item_id===item.id).map(h=><li key={h.id}>{h.entity}: {h.from_status?`${h.from_status} → `:''}{h.to_status} · {date(h.created_at)}</li>)}</ul></details>
 </article>;}
 return <section className="radar-workspace" aria-label="Research and sources">
  <p><Link href="/assets">← All Assets</Link></p>
  <div className="intro"><div><h2>Saved research &amp; ideas</h2><p>Collect hobby news and prepare your next post.</p><div className="button-row radar-shortcuts"><Button asChild><Link href="/requests?tab=editorial">Review stories &amp; drafts</Link></Button><Button variant="outline" asChild><Link href={tab==='releases'?'/calendar?tab=releases':'/calendar?tab=schedule'}>{tab==='releases'?'Release Calendar':'Open calendar'}</Link></Button></div></div>
  <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button disabled={offline}><Plus size={18}/>Add a link</Button></DialogTrigger><DialogContent className="radar-dialog"><DialogHeader><DialogTitle>Add a hobby story</DialogTitle><DialogDescription>Keep the original link and add the details you know. New links start unverified.</DialogDescription></DialogHeader>
  <form onSubmit={async e=>{e.preventDefault();const saved=await mutate({action:'add-item',data:{...link,sourceId:link.sourceId==='manual'?null:link.sourceId,category:link.category as Item['category'],kind:link.kind as Item['kind'],priority:link.priority as Item['priority'],publishedAt:link.publishedAt||null,eventDate:link.eventDate||null,tags:[...new Set(link.tags.split(',').map(t=>t.trim()).filter(Boolean))]}});if(saved){setLink(initialLink);setOpen(false);}}}>
   <label className="field"><span>Title</span><Input required maxLength={300} value={link.title} onChange={e=>setLink({...link,title:e.target.value})}/></label>
   <label className="field"><span>Original URL</span><Input type="url" required maxLength={2048} placeholder="https://…" value={link.url} onChange={e=>setLink({...link,url:e.target.value})}/></label>
   <Button type="button" variant="outline" disabled={disabled||!link.url} onClick={()=>void fillMetadata()}>Get available details</Button>{metadataNote&&<p role="status" className="muted">{metadataNote}</p>}
   <div className="form-grid"><Choice label="Category" value={link.category} options={CATEGORIES} onChange={category=>setLink({...link,category})}/><Choice label="Type" value={link.kind} options={KINDS} onChange={kind=>setLink({...link,kind})}/><Choice label="Source" value={link.sourceId} options={sources.filter(s=>s.value!=='all')} onChange={sourceId=>setLink({...link,sourceId})}/><Choice label="Priority" value={link.priority} options={PRIORITIES} onChange={priority=>setLink({...link,priority})}/><label className="field"><span>Publication date (optional)</span><Input type="date" value={link.publishedAt} onChange={e=>setLink({...link,publishedAt:e.target.value})}/></label><label className="field"><span>Release / event date (optional)</span><Input type="date" value={link.eventDate} onChange={e=>setLink({...link,eventDate:e.target.value})}/></label></div>
   <label className="field"><span>Summary / Northside angle</span><Textarea maxLength={4000} value={link.summary} onChange={e=>setLink({...link,summary:e.target.value})}/></label><label className="field"><span>Tags (comma separated, up to 12)</span><Input value={link.tags} onChange={e=>setLink({...link,tags:e.target.value})}/></label>
   {error&&<p role="alert" className="radar-error">{error}</p>}<Button type="submit" disabled={disabled}>{busy?'Saving…':'Save story'}</Button>
  </form></DialogContent></Dialog></div>
  {offline&&<div className="callout" role="status">You’re offline. Reconnect to load or save content. Unsaved input stays on this screen.</div>}
  {error&&<div className="radar-error" role="alert">{error} <Button variant="outline" onClick={()=>setReload(n=>n+1)}>Retry</Button></div>}
  {notice&&<p role="status" className="muted">{notice}</p>}
  <HqSubnavigation tabs={researchTabs} active={tab} label="Research areas"/>
   {filters.tab!=='sources'&&<section className="panel radar-filters" aria-label="Filter content"><label className="field radar-search"><span><Search size={15}/>Search</span><Input placeholder="Title, summary, tag or draft…" value={filters.q} onChange={e=>filter('q',e.target.value)}/></label><Collapsible className="radar-filter-disclosure"><CollapsibleTrigger asChild><Button variant="outline">Filters</Button></CollapsibleTrigger><CollapsibleContent className="radar-filter-options"><Choice label="Category" value={filters.category} options={['all',...CATEGORIES]} onChange={v=>filter('category',v)}/><Choice label="Source" value={filters.source} options={sources} onChange={v=>filter('source',v)}/><Choice label="Priority" value={filters.priority} options={['all',...PRIORITIES]} onChange={v=>filter('priority',v)}/><Choice label="Workflow status" value={filters.status} options={['all',...(filters.tab==='drafts'?DRAFT_STATUSES:STATUSES)]} onChange={v=>filter('status',v)}/><label className="field"><span>From</span><Input type="date" value={filters.after} onChange={e=>filter('after',e.target.value)}/></label><label className="field"><span>Through</span><Input type="date" value={filters.before} onChange={e=>filter('before',e.target.value)}/></label><Button variant="ghost" onClick={()=>setFilters({...emptyFilters,tab:filters.tab})}>Clear filters</Button><p className="muted radar-filter-note">Dates use publication date, or collection date when publication is unknown.</p></CollapsibleContent></Collapsible></section>}
   <div className="radar-results-line"><span role="status">{loading?'Loading content…':filters.tab==='sources'?`${data?.sources.length||0} sources`:`${data?.total||0} matching ${filters.tab==='drafts'?'ideas':'stories'}`}</span><div className="radar-actions"><Button variant="ghost" disabled={loading||offline} onClick={()=>setReload(n=>n+1)}>Reload view</Button><Button disabled={disabled} onClick={()=>void refreshSources()}><RefreshCw size={16}/>{collecting?'Collecting…':'Refresh now'}</Button></div></div>
   {loading&&<div className="panel radar-loading" aria-busy="true"><Radio/><p>Loading your hobby desk…</p></div>}
   {!loading&&data&&<>
   {['feed','releases','chase'].map(tab=><HqTabPanel active={filters.tab} value={tab} key={tab}>{!items.length?<Empty title={filters.q||filters.category!=='all'||filters.status!=='all'?'No matching stories':tab==='releases'?'No releases saved yet':tab==='chase'?'No chase cards saved yet':'Your research starts here'} text="Add a link from a trusted hobby source, or adjust your filters." action={()=>setOpen(true)}/>:<div className="radar-grid">{items.map(itemCard)}</div>}</HqTabPanel>)}
   <HqTabPanel active={filters.tab} value="drafts">{!items.length?<Empty title="No drafts in this view" text="Save an idea from a story to start a Northside caption, email or post." action={()=>filter('tab','feed')} label="Browse feed"/>:<div className="radar-grid">{items.map(item=>{const draft=data.drafts.find(d=>d.item_id===item.id);return draft&&<article className="panel radar-card" key={draft.id}><div className="radar-card-meta"><span className="tag blue">{item.category}</span><span className="tag">{draft.channel}</span><span className="tag">{draft.status}</span></div><h2>{draft.title}</h2><p className="radar-summary">{draft.body}</p><p className="muted">Updated {date(draft.updated_at)} · Source {item.verification}</p><div className="radar-actions"><Link href="/requests?tab=editorial">Edit in editorial queue</Link><a href={item.url} target="_blank" rel="noopener noreferrer">Original source <ArrowUpRight size={16}/></a></div><details className="radar-history"><summary>Workflow history</summary><ul>{data.history.filter(h=>h.item_id===item.id).map(h=><li key={h.id}>{h.entity}: {h.from_status?`${h.from_status} → `:''}{h.to_status} · {date(h.created_at)}</li>)}</ul></details></article>;})}</div>}<p className="muted">Drafts stay in Northside HQ. Review claims and availability before publishing through your usual channels.</p></HqTabPanel>
   <HqTabPanel active={filters.tab} value="sources"><SourcePanel sources={data.sources} runs={data.runs} disabled={disabled} onAdd={()=>setSourceOpen(true)} onLink={s=>{setMetadataNote('');setLink({...initialLink,sourceId:s.id,category:s.category,priority:s.priority});setOpen(true);}} onRefresh={refreshSources} onSave={mutate}/></HqTabPanel>
   {filters.tab!=='sources'&&(filters.offset>0||data.hasMore)&&<nav className="radar-actions" aria-label="Result pages"><Button disabled={!filters.offset} onClick={()=>setFilters({...filters,offset:Math.max(0,filters.offset-50)})}>Previous</Button><span>Page {Math.floor(filters.offset/50)+1}</span><Button disabled={!data.hasMore} onClick={()=>setFilters({...filters,offset:filters.offset+50})}>Next</Button></nav>}
   </>}

  <Dialog open={sourceOpen} onOpenChange={setSourceOpen}><DialogContent><DialogHeader><DialogTitle>Add a source</DialogTitle><DialogDescription>Save a publication or community page for staff to visit.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'add-source',data:{...source,category:source.category as Item['category']}})){setSourceOpen(false);setSource({name:'',url:'',category:'Baseball'});}}}><label className="field"><span>Source name</span><Input required maxLength={150} value={source.name} onChange={e=>setSource({...source,name:e.target.value})}/></label><label className="field"><span>Source URL</span><Input type="url" required maxLength={2048} value={source.url} onChange={e=>setSource({...source,url:e.target.value})}/></label><Choice label="Category" value={source.category} options={CATEGORIES} onChange={category=>setSource({...source,category})}/>{error&&<p role="alert" className="radar-error">{error}</p>}<Button type="submit" disabled={disabled}>Save source</Button></form></DialogContent></Dialog>
  <Dialog open={!!editing} onOpenChange={v=>{if(!v)setEditing(null);}}><DialogContent className="radar-dialog"><DialogHeader><DialogTitle>Shape your Northside draft</DialogTitle><DialogDescription>Add your shop’s angle and check the original story. Saving does not publish.</DialogDescription></DialogHeader>{editing&&<form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'edit-draft',id:editing.id,title:editing.title,body:editing.body,channel:editing.channel,status:editing.status}))setEditing(null);}}><label className="field"><span>Title</span><Input required maxLength={300} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label className="field"><span>Caption / copy</span><Textarea rows={9} maxLength={10000} value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})}/></label><div className="form-grid"><Choice label="Channel" value={editing.channel} options={CHANNELS} onChange={channel=>setEditing({...editing,channel:channel as Draft['channel']})}/><Choice label="Draft status" value={editing.status} options={DRAFT_STATUSES} onChange={status=>setEditing({...editing,status:status as Draft['status']})}/></div>{error&&<p role="alert" className="radar-error">{error}</p>}<Button type="submit" disabled={disabled}>{busy?'Saving…':'Save draft'}</Button></form>}</DialogContent></Dialog>
 </section>;
}
function Empty({title,text,action,label='Add a link'}:{title:string;text:string;action:()=>void;label?:string}){return <section className="panel radar-empty"><RadarIcon size={36}/><h2>{title}</h2><p>{text}</p><Button variant="outline" onClick={action}>{label}</Button></section>;}
