'use client';
import {Assignee, EmptyState, StatusBadge, PageHelp} from '@/components/hq-ui';
import {clientId} from '@/lib/client-id';
import Link from 'next/link';
import {chicagoDate} from '@/lib/content-radar/dates';
import {useEffect,useState} from 'react';
import {blankDetail,blankQueue,type RecordRow,type Queue,type Product,type Team} from '@/lib/content-radar/editorial-model';
import type {readEditorial} from '@/lib/content-radar/editorial-repository';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
type Data=Awaited<ReturnType<typeof readEditorial>>;
type Editor={id:string;kind:RecordRow['kind'];version:number;data:Record<string,unknown>};
const labels:Record<string,string>={itemId:'Source story',state:'Editorial state',assignee:'Assignee',facebook:'Facebook caption',instagram:'Instagram caption',reel:'Short Reel outline',references:'Source links (one per line)',cta:'Northside call to action',original:'Northside original',assetId:'Uploaded asset',attribution:'Creator / customer attribution',permission:'Media reuse permission',permissionEvidence:'Permission record or consent notes',calendarDate:'Calendar date and time (America/Chicago)',calendarChannel:'Calendar caption',certainty:'Evidence status',evidence:'Evidence URL',manufacturerDate:'Manufacturer release date',manufacturerSource:'Manufacturer date source',arrivalDate:'Northside confirmed arrival',arrivalSource:'Northside arrival confirmation source',card:'Exact card name / number',player:'Player or Pokémon',parallel:'Parallel / edition',numbering:'Serial number / print run',eligibleFormats:'Eligible product formats',pullStatus:'Reported pull status',pullEvidence:'Pull status evidence URL',pullAsOf:'Pull status as of',saleType:'Sale type',price:'Amount',currency:'Currency (ISO code)',saleDate:'Sale or listing date',grade:'Grade and grader',buyerPremium:'Buyer premium treatment',confirmedAt:'Availability confirmed on',userId:'Account reference (read only)',active:'Login active',role:'Access role',title:'Title',status:'Watchlist status'};
const choices:Record<string,string[]>={state:['Saved','Draft','Needs review','Approved','Archived'],topic:['story','release','checklist','delay','official announcement','chase','pull','sale','event'],certainty:['incomplete','rumor','reported','confirmed'],pullStatus:['unknown','reported pulled','confirmed pulled','reported unpulled'],saleType:['unknown','asking','completed'],buyerPremium:['unknown','included','excluded','not applicable'],permission:['unknown','owned','granted','denied'],original:['none','customer pull','staff pick','break highlight','grading return','Boomski clip'],calendarChannel:['facebook','instagram'],status:['carried','incoming','watching','unavailable'],role:['admin','staff']};
export default function Editorial({initialTab='Editorial queue'}:{initialTab?:string}){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState(initialTab),[editor,setEditor]=useState<Editor|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[state,setState]=useState('all');
 async function load(){const r=await fetch('/api/content-radar/editorial',{cache:'no-store'});const j=await r.json() as Data & {error?:string};if(!r.ok)throw Error(j.error);setData(j);}
 useEffect(()=>{const controller=new AbortController();fetch('/api/content-radar/editorial',{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json() as Data & {error?:string};if(!r.ok)throw Error(j.error);setData(j);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return ()=>controller.abort();},[]);
 useEffect(()=>{
   if(!data||initialTab!=='Editorial queue')return;
   const sync=()=>{
     const hash=window.location.hash;
     if(hash==='#new-post'){setEditor({kind:'queue',id:clientId(),version:0,data:{...blankQueue}});window.history.replaceState(null,'',window.location.pathname+window.location.search);}
     else if(hash.startsWith('#post-')) {
       let id='';try{id=decodeURIComponent(hash.slice(6));}catch{return;}
       const row=data.records.find(r=>r.kind==='queue'&&r.id===id);
       if(row){setEditor({kind:'queue',id,version:row.version,data:structuredClone(row.data) as Record<string,unknown>});window.history.replaceState(null,'',window.location.pathname+window.location.search);}
     }
   };
   sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);
 },[data,initialTab]);
 async function save(){if(!editor)return;setBusy(true);setError('');try{const r=await fetch('/api/content-radar/editorial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editor)});const j=await r.json() as {error?:string;data?:Queue};if(!r.ok)throw Error(j.error);setEditor(null);setNotice('Saved. '+(j.data?.state==='Needs review'?'This draft needs review.':''));await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function edit(kind:Editor['kind'],id:string,initial:Record<string,unknown>){const r=data?.records.find(r=>r.kind===kind&&r.id===id);setEditor({kind,id,version:r?.version||0,data:structuredClone(r?.data||initial)});setError('');setNotice('');requestAnimationFrame(()=>document.querySelector('.editor-dialog')?.scrollIntoView({behavior:'smooth',block:'start'}));}
 function field(key:string,value:unknown,change:(v:unknown)=>void){
 if(key==='assetOwner'||key==='itemId'||key==='userId')return null;
 if(key==='product')return <fieldset key={key}><legend>Exact product</legend><div className="two-fields">{Object.entries(value as object).map(([k,v])=>field(k,v,n=>change({...value as object,[k]:n})))}</div></fieldset>;
 const label=labels[key]||key.charAt(0).toUpperCase()+key.slice(1);let options=choices[key];if(key==='assignee')options=['',...team.filter(r=>r.data.active||r.id===value).map(r=>r.id)];if(key==='assetId')options=['',...(data?.assets.map(a=>a.id)||[]),...(typeof value==='string'&&value&&!data?.assets.some(a=>a.id===value)?[value]:[])];
 return <label className="editor-field" key={key}><span>{label}</span>{typeof value==='boolean'?<input type="checkbox" checked={value} onChange={e=>change(e.target.checked)}/>:options?<select value={String(value)} onChange={e=>change(e.target.value)}>{options.map(o=><option key={o} value={o}>{key==='assetId'?(data?.assets.find(a=>a.id===o)?.name||o||'No asset'):key==='assignee'?(team.find(r=>r.id===o)?.data.name||'Unassigned'):o}</option>)}</select>:key==='product'?<div className="two-fields">{Object.entries(value as object).map(([k,v])=>field(k,v,n=>change({...value as object,[k]:n})))}</div>:['notes','facebook','instagram','reel','references','permissionEvidence'].includes(key)?<Textarea rows={key==='reel'?5:3} value={Array.isArray(value)?value.join('\n'):String(value)} onChange={e=>change(key==='references'?e.target.value.split('\n').filter(Boolean):e.target.value)}/>:<Input placeholder={key==='calendarDate'?'YYYY-MM-DDTHH:mm, e.g. 2026-09-20T10:00':undefined} type={key==='calendarDate'?'text':/Date$|AsOf$|confirmedAt/.test(key)?'date':'text'} value={String(value)} onChange={e=>change(e.target.value)} onBlur={e=>change(e.target.value)}/>}</label>;
 }
 const rows=data?.records||[];const team=rows.filter(r=>r.kind==='team').map(r=>({id:r.id,data:r.data as Team}));const drafts=rows.filter(r=>r.kind==='queue'&&(state==='all'||r.data.state===state));
 return <section className="editorial-workspace" aria-label="Content requests and review"><style>{`.button-row{display:flex;gap:12px;flex-wrap:wrap}.editor-nav{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0}.editor-field{display:flex;flex-direction:column;gap:6px;margin:12px 0}.editor-field>span{font-weight:600}.editor-field select{padding:10px;border:1px solid var(--input);border-radius:8px;background:var(--card);color:var(--foreground)}.editor-card{margin:16px 0;overflow-wrap:anywhere}.editor-layout>*{min-width:0}.editor-dialog button{white-space:normal;height:auto;min-height:36px;max-width:100%}.editor-dialog input,.editor-dialog select,.editor-dialog textarea{max-width:100%}.editor-nav button{white-space:normal}.editor-dialog{scroll-margin-top:20px}.editor-history{max-height:360px;overflow:auto}.editor-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(300px,1fr);gap:24px}.editor-dialog{border:2px solid #00a7e9;border-radius:16px;padding:24px;background:var(--card);color:var(--foreground);margin-bottom:24px}.editor-dialog .button-row{position:sticky;bottom:0;background:var(--card);padding:12px 0}.editor-why{font-size:1rem}.editor-note{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:800px){.editor-layout{grid-template-columns:1fr;gap:8px}.editor-field{margin:6px 0}.editor-dialog{padding:16px}}`}</style>
 {initialTab!=='Staff'&&<nav className="hq-editor-nav" aria-label="Editorial views"><div className="hq-view-switch"><Button variant="ghost" aria-pressed={tab==='Editorial queue'} onClick={()=>setTab('Editorial queue')}>Posts &amp; review</Button></div><details className="hq-more-views"><summary>Content tools</summary><div className="button-row">{['Today’s Top 5','Stories','Products'].map(t=><Button key={t} variant="outline" aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</Button>)}<Button variant="outline" asChild><Link href="/assets/research">Research &amp; sources</Link></Button></div></details></nav>}
 {tab!=='Editorial queue'&&tab!=='Staff'&&<h2>{tab}</h2>}
 {error&&<p role="alert" className="notice">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}{!data&&!error&&<p>Loading staff workspace…</p>}
 {editor&&<section className="editor-dialog" aria-label="Record editor"><h2>{editor.kind==='queue'?'Northside draft':editor.kind==='detail'?'Release and card facts':editor.kind==='team'?'Staff login':'Product watchlist'}</h2>
 {editor.kind==='queue'&&<><p>Use plain collector language. Keep rumors labeled. Do not invent prices, stock, dates or Northside involvement. An unknown pull status stays unknown.</p><p>Upload media in Assets first. Uploads are shared with authorized team members.</p></>}
 {editor.kind==='team'&&<p>Approve the correct email address for each person. They must verify that email when creating their login. Titles do not grant administrator access. Nick and Nik are separate people.</p>}
 {editor.kind==='detail'&&<p>Keep manufacturer dates separate from Northside arrivals. A reported unpulled status is a dated report, never a current guarantee. Sale amounts must distinguish asking prices from completed sales.</p>}
 <div className="editor-layout">{Object.entries(editor.data).map(([k,v])=>field(k,v,n=>setEditor({...editor,data:{...editor.data,[k]:n}})))}</div>
 <div className="button-row"><Button disabled={busy} onClick={save}>Save changes</Button><Button variant="outline" disabled={busy} onClick={()=>setEditor(null)}>Cancel</Button></div>
 <details><summary>Change history</summary><div className="editor-history">{data?.history.filter(h=>h.kind===editor.kind&&h.record_id===editor.id).map(h=><article key={String(h.id)}><p>Version {String(h.version)} · {chicagoDate(String(h.created_at))} · {String(h.actor)}</p><dl>{Object.entries(h.data as Record<string,unknown>).filter(([k])=>!['assetOwner','itemId'].includes(k)).map(([k,v])=><div key={k}><dt>{labels[k]||k}</dt><dd className="editor-note">{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl></article>)}</div></details></section>}
 {data&&['Today’s Top 5','Stories'].includes(tab)&&<><details><summary>Daily collection history</summary>{data.jobs.length?data.jobs.map(j=><p key={j.id}>{j.id} UTC · {j.data.status} · {chicagoDate(j.updated_at)}</p>):<p>No scheduled runs recorded. Daily collection needs hosting configuration.</p>}</details><p>Last successful collection: {chicagoDate(data.lastRefresh)}. {data.rankingScope} Today’s selection is recalculated in America/Chicago: {new Date().toLocaleDateString('en-US',{timeZone:'America/Chicago'})}.</p>{(tab==='Today’s Top 5'?data.top5:data.items).map(i=><article className="panel editor-card" key={i.id}><p className="eyebrow">{i.score} POINTS · {i.certainty.toUpperCase()}</p><h2>{i.title}</h2><p>{i.summary}</p><p>Published: {chicagoDate(i.published_at)} · {i.availability}</p><ul className="editor-why">{i.reasons.map((r,n)=><li key={n}>{r.points>0?'+':''}{r.points}: {r.reason}</li>)}</ul><div className="button-row"><a href={i.url} target="_blank" rel="noopener noreferrer">Original source</a><Button variant="outline" onClick={()=>edit('detail',i.id,blankDetail)}>Edit structured facts</Button><Button onClick={()=>edit('queue',i.id,{...blankQueue,itemId:i.id,title:i.title,references:[i.url]})}>Save / draft story</Button></div></article>)}{!data.items.length&&<p>No stories yet. Refresh the publisher sources or add a link in Research & sources.</p>}</>}
 {tab==='Editorial queue'&&data&&<><div className="button-row"><Button onClick={()=>edit('queue',clientId(),{...blankQueue,original:'staff pick'})}>Create Post</Button><label>Filter state <select value={state} onChange={e=>setState(e.target.value)}>{['all',...choices.state].map(s=><option key={s}>{s}</option>)}</select></label></div><p className="muted">Review posts here, then hand approved content to production in Work.</p>{drafts.map(r=>{const q=r.data as Queue;return <article className="panel editor-card" key={r.id}><div className="hq-card-top">{q.state==='Archived'?<span className="tag">Archived</span>:<StatusBadge status={q.state==='Needs review'?'in_review':q.state==='Approved'?'on_track':'not_started'} detail={q.state}/>}<Assignee name={team.find(t=>t.id===q.assignee)?.data.name||'Unassigned'}/></div><h2>{q.title}</h2><p className="editor-note">{q.facebook||q.instagram||'Captions not drafted yet.'}</p><p>{q.notes}</p>{q.assetId&&<a href={'/api/content-radar/media/'+r.id} target="_blank" rel="noopener noreferrer">Open attached media</a>}<div className="button-row">{data.handoffs[r.id]&&<Link href={'/projects/work/'+data.handoffs[r.id]}>Open HQ production and publishing →</Link>}<Button variant="outline" onClick={()=>edit('queue',r.id,q)}>{data.handoffs[r.id]?'Review source (requires renewed HQ approval)':'Edit / review'}</Button><Button variant="outline" disabled={!!data.handoffs[r.id]||busy||q.state!=='Approved'||!q.calendarDate} onClick={async()=>{setBusy(true);try{const res=await fetch('/api/content-radar/editorial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'calendar',id:r.id})});const j=await res.json() as {error?:string};if(!res.ok)throw Error(j.error);setNotice('Added to the Northside HQ calendar. Nothing was published.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Add approved draft to team calendar</Button></div></article>;})}{!drafts.length&&<EmptyState title="No posts in this view" description="Create a post or choose another state."/>}</>}
 {tab==='Products'&&data&&<><p>Shopify is not connected. Staff confirmations apply only to the exact year, set, sport and format. “Carried” is not a live stock count.</p><Button onClick={()=>edit('product',clientId(),{year:'',set:'',sport:'',format:'',status:'watching',evidence:'',confirmedAt:'',notes:''})}>Add product</Button>{rows.filter(r=>r.kind==='product').map(r=>{const p=r.data as Product;return <article className="panel editor-card" key={r.id}><h2>{p.year} {p.set}</h2><p>{p.sport} · {p.format} · {p.status}</p><p>{p.confirmedAt||'Not confirmed'} · {p.notes}</p><Button onClick={()=>edit('product',r.id,p)}>Edit product and history</Button></article>;})}</>}
 {tab==='Staff'&&data&&<><p className="muted">Staff profiles and access to Northside HQ.</p><div className="hq-team-grid">{team.map(({id,data:t})=><article className="panel hq-team-card" key={id}><div className="hq-card-top"><Assignee name={t.name}/><span className="tag">{t.active?'Active':'Pending login'}</span></div><h2>{t.name}</h2><p>{t.title||'Team member'} · {t.role==='admin'?'Administrator':'Staff'}</p><p className="muted">{t.email||'Email not recorded'}</p>{data.admin&&<Button variant="outline" onClick={()=>edit('team',id,t)}>Manage staff access</Button>}</article>)}</div>{!team.length&&<section className="panel"><EmptyState title="No staff profiles available" description="Staff profiles show who can access the workspace. Contact Steven if your team is missing." action={<Button variant="outline" onClick={()=>void load().catch(e=>setError(e.message))}>Reload Team</Button>}/></section>}<PageHelp title="Staff access requirements"><p>Use individual team logins with the approved email shown above. A verified email is required. Only an administrator can change access.</p></PageHelp></>}

 </section>;
}
